name: Deploy PrestaShop to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY2 }}

    - name: Rsync files to EC2
      run: |
        rsync -avz --delete ./ ubuntu@${{ secrets.EC2_HOST2 }}:/var/www/html/ \
          --exclude='.git' \
          --exclude='.github'

    - name: Restart Apache
      run: |
        ssh ubuntu@${{ secrets.EC2_HOST2 }} 'sudo systemctl restart apache2'
